spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jaco_db
    username: postgres
    password:
  cache.type: redis
  redis:
    host:
      localhost
    port:
      6379

jpa.show-sql: true

vendorAPI:
  url: https://www.abibliadigital.com.br/api/
  username: yourUsername
  password: yourPassword