spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jaco_db
    username: postgres
    password:

jpa.show-sql: true

vendorAPI:
  url: https://www.abibliadigital.com.br/api/
  username: yourUsername
  password: yourPassword